from enum import StrEnum


class ActorRole(StrEnum):
    STUDENT = "STUDENT"
    LECTURER = "LECTURER"
    ACADEMIC_AFFAIRS = "ACADEMIC_AFFAIRS"


class EscalationTarget(StrEnum):
    COURSE_LECTURER = "COURSE_LECTURER"
    ACADEMIC_AFFAIRS = "ACADEMIC_AFFAIRS"
    POLICY_VIOLATION = "POLICY_VIOLATION"


class DocumentStatus(StrEnum):
    PENDING = "PENDING"
    INGESTING = "INGESTING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class QuestionStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    ANSWERED = "ANSWERED"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    CLARIFICATION_RECEIVED = "CLARIFICATION_RECEIVED"
    ESCALATED = "ESCALATED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    REJECTED = "REJECTED"


class Route(StrEnum):
    ANSWER = "ANSWER"
    CLARIFY = "CLARIFY"
    ESCALATE = "ESCALATE"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    REJECT = "REJECT"


class UncertaintyType(StrEnum):
    NONE = "NONE"
    MISSING_FACT = "MISSING_FACT"
    OUT_OF_POLICY = "OUT_OF_POLICY"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    SUSPICIOUS_INPUT = "SUSPICIOUS_INPUT"
    AI_UNAVAILABLE = "AI_UNAVAILABLE"


class CaseStatus(StrEnum):
    UNDER_REVIEW = "UNDER_REVIEW"
    WAITING_FOR_STUDENT = "WAITING_FOR_STUDENT"
    FORWARDED = "FORWARDED"
    CANCELLED = "CANCELLED"
    DECIDED = "DECIDED"


class DecisionValue(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEED_MORE_INFO = "NEED_MORE_INFO"
    FORWARDED = "FORWARDED"


class ScopeType(StrEnum):
    STUDENT = "STUDENT"
    GROUP = "GROUP"
    COURSE = "COURSE"


class PolicyCoverage(StrEnum):
    DIRECT = "DIRECT"
    CONDITIONAL = "CONDITIONAL"
    APPLICABLE_EXCEPTION = "APPLICABLE_EXCEPTION"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    REQUESTS_WAIVER = "REQUESTS_WAIVER"
    MISSING_FACT = "MISSING_FACT"
    NO_POLICY = "NO_POLICY"
    CONFLICTING = "CONFLICTING"
    SUSPICIOUS = "SUSPICIOUS"
    AI_UNAVAILABLE = "AI_UNAVAILABLE"
    UNRESOLVED = "UNRESOLVED"


class ExceptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"

